# Site settings
title: 清风工资条
SEOTitle: 清风工资条 - Excel工资表秒变工资条
header-img: img/post-bg-desk.jpg
email: pay2021@yeah.net
description: "Excel工资表秒变工资条，智能导入，一键群发"
keyword: "工资条, 工资条邮件群发, 邮件群发,工资表转工资条,excel工资表转html工资条"
url: "https://nolansoft.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/nolansoft/nolansoft.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you're going to be!"
sidebar-avatar: /img/about_ww.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
 weibo_username:     lnddsi
# zhihu_username:     qiubaiying
# github_username:    qiubaiying
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID:b64716557e8cf38e811b                             #生成的clientID
  clientSecret:166e3408ec2176879cba7b8b10889d5f5def91bd     #生成的clientSecret
  repo: nolansoft.github.io    #仓库名称
  owner: nolansoft    #github用户名
  admin: nolansoft
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接，请尽量不要删除，谢谢！
friends: [
{
title:"水木软件",
href:"http://waterwoodsoftware.com"
},
    {
        title: "格罗比言·全球语",
        href: "https://globien.gitee.io"
    },{
        title: "格罗比言互动社区",
        href: "https://tieba.baidu.com/f?kw=%E6%A0%BC%E7%BD%97%E6%AF%94%E8%A8%80&fr=home"
    },{
        title: "知乎：人造国际语",
        href: "https://zhuanlan.zhihu.com/Artificial-International-Language"
    }
]
